# Generated by Django 4.2.6 on 2023-10-30 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_edit_books', 'Create, update, and delete books'),)},
        ),
    ]
